name: GoogleTests_template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    - name: Create build folder inside tests folder
      run: cd /home/runner/work/otus_homework_-/otus_homework_-/tests && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: Make tests with CMakeLists
      run: cd /home/runner/work/otus_homework_-/otus_homework_-/tests && cd build && make
    - name: Run Tests
      run: /home/runner/work/otus_homework_-/otus_homework_-/tests/build/test_module
